version: '3.9'

services:
  analytics:
    build:
      context: ./analysis-service
      dockerfile: Dockerfile
    container_name: analysis-service
    restart: on-failure
    depends_on:
      - postgres
      - zookeeper
      - kafka
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./analysis-service/certs:/certs
    networks:
      - app-net

  upload:
    build:
      context: ./upload-service
      dockerfile: Dockerfile
    container_name: upload-service
    restart: on-failure
    ports:
      - "8081:8081"
    env_file:
      - .env    
    networks:
      - app-net

  postgres:
    image: postgres:17
    container_name: test
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rbkkth3920
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,SSL:SSL
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,SSL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,SSL://kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      # TLS через JKS
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: key_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: truststore_creds
      KAFKA_SSL_CLIENT_AUTH: none
    volumes:
      - ./service-analytics/certs:/etc/kafka/secrets
    depends_on:
      - zookeeper
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  pgdata:
