### Получить все жанры
GET http://localhost:8081/genres
Accept: application/json

### Получить всех артистов
GET http://localhost:8081/artists
Accept: application/json

### Получить артиста по ID
GET http://localhost:8081/artists/2
Accept: application/json

### Получить все альбомы
GET http://localhost:8081/albums
Accept: application/json

### Получить альбом по ID
GET http://localhost:8081/albums/1
Accept: application/json

### Получить все песни
GET http://localhost:8081/songs
Accept: application/json

### Получить песню по ID
GET http://localhost:8081/songs/1
Accept: application/json





### Создать жанр (только admin)
POST http://localhost:8081/genres
Content-Type: application/json
Authorization: admintoken

{
  "name": "Classical"
}

### Обновить жанр (только admin)
PUT http://localhost:8081/genres/1
Content-Type: application/json
Authorization: admintoken

{
  "name": "UpdatedGenreName"
}




### Зарегистрировать артиста (artist)
POST http://localhost:8081/artists/register/me
Content-Type: application/json
Authorization: artisttoken

{
  "name": "NewArtist"
}

### Обновить данные артиста (artist или admin)
PUT http://localhost:8081/artists/4
Content-Type: application/json
Authorization: artisttoken

{
  "name": "ArtistRenamed"
}




### Создать песню (artist)
POST http://localhost:8081/songs
Content-Type: application/json
Authorization: artisttoken

{
  "name": "MySong",
  "genre_id": 1,
  "link": "http://example.com/track.mp3",
  "artist_ids": []
}

### Обновить песню (artist)
PUT http://localhost:8081/songs/4
Content-Type: application/json
Authorization: artisttoken

{
  "name": "MySong (Remastered)",
  "genre_id": 1,
  "link": "http://example.com/track-remastered.mp3"
}




### Создать альбом (artist)
POST http://localhost:8081/albums
Content-Type: application/json
Authorization: artisttoken

{
  "name": "MyAlbum",
  "genre_id": 1,
  "song_ids": [1]
}

### Обновить альбом (artist)
PUT http://localhost:8081/albums/7
Authorization: artisttoken

{
  "name": "MyAlbum (Deluxe)",
  "genre_id": 2
}